var allProducts = [
    {
        title: 'The Sail @Marina Bay',
        img: '1.jpg',
        district: 'D-15 Katong',
        tenure: 'freehold',
        developmentyear: '2010',
        mrtnearest: 'MRT Tanjong Pagar',
        mrttime: '2 mins',
        cbd_car: '5 mins',
        cbd_bus: '10 mins',
        avg_psf: 'S$ X,XXX PSF',
        avg_sales: 'X,XXX',
        sale_liquidity: 'S$ X,XXX,XXX',
        avg_rental_psf: 'S$ X,XXX PSF',
        rent_liquidity_index: 'S# X,XXX,XXX',
        avg_rental_yield: 'X.X%',
        condominium_height: 'Low Rise',
        amenities: 'BBQ, Pool, Gym, Playground, Tennis'
    },
    {
        title: 'Condo 01',
        img: '2.jpg',
        district: 'D-16 Katong',
        tenure: 'freehold',
        developmentyear: '2012',
        mrtnearest: 'MRT Tanjong Pagar',
        mrttime: '2 mins',
        cbd_car: '6 mins',
        cbd_bus: '10 mins',
        avg_psf: 'S$ Y,YYY PSF',
        avg_sales: 'Y,YYY',
        sale_liquidity: 'S$ Y,YYY,YYY',
        avg_rental_psf: 'S$ Y,YYY PSF',
        rent_liquidity_index: 'S# Y,YYY,YYY',
        avg_rental_yield: 'Y.Y%',
        condominium_height: 'Low Rise',
        amenities: 'BBQ, Pool, Gym, Playground, Tennis'
    },
    {
        title: 'Condo 02',
        img: '3.jpg',
        district: 'D-17 Katong',
        tenure: 'freehold',
        developmentyear: '2014',
        mrtnearest: 'MRT Tanjong Pagar',
        mrttime: '2 mins',
        cbd_car: '7 mins',
        cbd_bus: '10 mins',
        avg_psf: 'S$ Z,ZZZ PSF',
        avg_sales: 'Z,ZZZ',
        sale_liquidity: 'S$ Z,ZZZ,ZZZ',
        avg_rental_psf: 'S$ Z,ZZZ PSF',
        rent_liquidity_index: 'S# Z,ZZZ,ZZZ',
        avg_rental_yield: 'Z.Z%',
        condominium_height: 'Low Rise',
        amenities: 'BBQ, Pool, Gym, Playground, Tennis'
    },
    {
        title: 'Condo 03',
        img: '4.jpg',
        district: 'D-18 Katong',
        tenure: 'freehold',
        developmentyear: '2016',
        mrtnearest: 'MRT Tanjong Pagar',
        mrttime: '2 mins',
        cbd_car: '8 mins',
        cbd_bus: '10 mins',
        avg_psf: 'S$ A,AAA PSF',
        avg_sales: 'A,AAA',
        sale_liquidity: 'S$ A,AAA,AAA',
        avg_rental_psf: 'S$ A,AAA PSF',
        rent_liquidity_index: 'S# A,AAA,AAA',
        avg_rental_yield: 'A.A%',
        condominium_height: 'Low Rise',
        amenities: 'BBQ, Pool, Gym, Playground, Tennis'
    },
];